name: DebugBuild
on:
  push:
    branches:
      - main

env:
  SOLUTION_FILE_PATH: game.sln
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to Path
        uses: microsoft/setup-msbuild@v2
      
      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
    
